export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOAD_PROFILE = "LOAD_PROFILE";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";

export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";
export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";

export const SELECTED_VIDEOS_REQUEST = "SELECTED_VIDEOS_REQUEST";
export const SELECTED_VIDEOS_SUCCESS = "SELECTED_VIDEOS_SUCCESS";
export const SELECTED_VIDEOS_FAIL = "SELECTED_VIDEOS_FAIL";

export const CHANNEL_DETAILS_REQUEST = "CHANNEL_VIDEOS_REQUEST";
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_VIDEOS_SUCCESS";
export const CHANNEL_DETAILS_FAIL = "CHANNEL_VIDEOS_FAIL";

export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";
export const COMMENT_LIST_FAIL = "COMMENT_LIST_FAIL";

export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";

export const RELATED_VIDEO_REQUEST = "RELATED_VIDEO_REQUEST";
export const RELATED_VIDEO_SUCCESS = "RELATED_VIDEO_SUCCESS";
export const RELATED_VIDEO_FAIL = "RELATED_VIDEO_FAIL";

export const Search_VIDEO_REQUEST = "Search_VIDEO_REQUEST";
export const Search_VIDEO_SUCCESS = "Search_VIDEO_SUCCESS";
export const Search_VIDEO_FAIL = "Search_VIDEO_FAIL";